In [ ]:
import numpy as np
import cv2

img = cv2.imread('perspective.jpg',0)

pts1 = np.float32([[28,30],[181,25],[13,190],[193,190]])
pts2 = np.float32([[0,0],[300,0],[0,300],[300,300]])

M = cv2.getPerspectiveTransform(pts1,pts2)
img = cv2.warpPerspective(img,M,(300,300))

img = cv2.Canny(img,100,200)


cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt
img = cv.imread('perspective.jpg',0)
img = cv.medianBlur(img,5)
ret,th1 = cv.threshold(img,127,255,cv.THRESH_BINARY)
th2 = cv.adaptiveThreshold(img,255,cv.ADAPTIVE_THRESH_MEAN_C,\
            cv.THRESH_BINARY,11,2)
th3 = cv.adaptiveThreshold(img,255,cv.ADAPTIVE_THRESH_GAUSSIAN_C,\
            cv.THRESH_BINARY,11,2)
titles = ['Original Image', 'Global Thresholding (v = 127)',
            'Adaptive Mean Thresholding', 'Adaptive Gaussian Thresholding']
images = [img, th1, th2, th3]
for i in range(4):
    plt.subplot(2,2,i+1),plt.imshow(images[i],'gray')
    plt.title(titles[i])
    plt.xticks([]),plt.yticks([])
plt.show()

<Figure size 640x480 with 4 Axes>

In [3]:
import numpy as np
import cv2 as cv

filename = 'DSC_0480.JPG'
img = cv.imread(filename)
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
gray = np.float32(gray)
dst = cv.cornerHarris(gray,2,3,0.04)
#result is dilated for marking the corners, not important
dst = cv.dilate(dst,None)
# Threshold for an optimal value, it may vary depending on the image.
img[dst>0.01*dst.max()]=[0,0,255]
cv.imshow('dst',img)
if cv.waitKey(0) & 0xff == 27:
    cv.destroyAllWindows()

In [4]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)
while(1):
    _, frame = cap.read()
    orignal = frame.copy()
    
    """"
    lower_blue = np.array([0,50,50])
    upper_blue = np.array([130,255,255])
    
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    # Bitwise-AND mask and original image
    frame = cv2.bitwise_and(frame,frame, mask= mask)
    """
    
    frame = cv2.blur(frame,(40,40))
    
    
    cv2.imshow('frame1',frame)
    
    b = frame[:, :, 0]
    g = frame[:, :, 1]
    r = frame[:, :, 2]
    
    cv2.imshow('frame2',r)
    cv2.imshow('frame3',g)
    cv2.imshow('frame4',b)
    
    max_chanel = np.maximum(r.copy(), np.maximum(g.copy(), b.copy()))
    
    b = np.array(b == max_chanel, dtype=int)
    g = np.array(g == max_chanel, dtype=int)
    r = np.array(r == max_chanel, dtype=int)

    b[b == 1] = 255
    g[g == 1] = 255
    r[r == 1] = 255
    
    frame[:, :, 0] = b
    frame[:, :, 1] = g
    frame[:, :, 2] = r
    
    cv2.imshow('frame5',frame)
    
    frame = cv2.medianBlur(frame,15)
    frame = cv2.Canny(frame,100, 200)
    
    
    rows, cols = np.where(frame == 255)
    for i,j in zip(rows, cols):
        orignal[i][j] = [255, 0, 0]
    

#     print(frame.shape)
#     print(orignal.shape)
    cv2.imshow('frame6',frame)
    cv2.imshow('frame7',orignal)

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

In [7]:
cap.release()

In [6]:
A = np.random.rand(1,2,3)
# array([[[ 0.79188   ,  0.32707664,  0.18386629],
#         [ 0.4139146 ,  0.07259663,  0.47604274]]])

B = np.array([0.1, 0.2, 0.3])

C = np.maximum(A, B)
# array([[[ 0.1       ,  0.2       ,  0.18386629],
#         [ 0.1       ,  0.07259663,  0.3       ]]])
print(A)
print(B)
print(C)

[[[0.43385525 0.86277201 0.03682685]
  [0.66794925 0.07158107 0.68908011]]]
[0.1 0.2 0.3]
[[[0.43385525 0.86277201 0.3       ]
  [0.66794925 0.2        0.68908011]]]
